import logging

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-9s %(message)s",
    force=True,
)

"""
Manual smoke-test for the OrchestratorAgent.

Usage:
    python test_orchestrator.py

What it does:
    1. Clears stale 'events' and 'commands' lists in Redis.
    2. Pushes a fake crowd-anomaly event.
    3. Runs the OrchestratorAgent in a background thread for 10 seconds.
    4. Prints every command the orchestrator dispatched to Redis.
"""

import json
import os
import threading
import time

import redis
from dotenv import load_dotenv

from agents.orchestrator import OrchestratorAgent

load_dotenv()

logger = logging.getLogger(__name__)

REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
RUN_DURATION = 10  # seconds


def get_redis() -> redis.Redis:
    return redis.Redis.from_url(REDIS_URL, decode_responses=True)


def seed_event(r: redis.Redis) -> None:
    fake_event = "crowd anomaly at Gate 4, severity 0.83"
    r.rpush("events", fake_event)
    logger.info("Seeded event: '%s'", fake_event)


def collect_commands(r: redis.Redis) -> list[dict]:
    """Read and clear all entries from the 'commands' list."""
    pipe = r.pipeline()
    pipe.lrange("commands", 0, -1)
    pipe.delete("commands")
    results = pipe.execute()
    raw_list: list[str] = results[0]

    commands = []
    for raw in raw_list:
        try:
            commands.append(json.loads(raw))
        except json.JSONDecodeError:
            commands.append({"raw": raw})
    return commands


def main() -> None:
    r = get_redis()

    # Clean slate
    r.delete("events", "commands", "agent_reports")

    seed_event(r)

    agent = OrchestratorAgent()
    thread = threading.Thread(target=agent.run, daemon=True, name="orchestrator")
    thread.start()

    logger.info("Orchestrator running for %d seconds — collecting commands…", RUN_DURATION)
    time.sleep(RUN_DURATION)

    agent.stop()
    thread.join(timeout=5)

    commands = collect_commands(r)

    print("\n" + "=" * 50)
    print("  Commands generated by OrchestratorAgent")
    print("=" * 50)
    if commands:
        for i, cmd in enumerate(commands, 1):
            print(f"\n[{i}]  {json.dumps(cmd, indent=4)}")
    else:
        print("\n  (no commands generated)")
    print()


if __name__ == "__main__":
    main()
