import logging

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-9s %(message)s",
    force=True,
)

import json
import os
import threading
import time

import redis
from dotenv import load_dotenv

from agents.perception import PerceptionAgent

load_dotenv()

logger = logging.getLogger(__name__)

REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
RUN_DURATION = 10  # seconds


def get_redis() -> redis.Redis:
    return redis.Redis.from_url(REDIS_URL, decode_responses=True)


def seed_command(r: redis.Redis) -> None:
    cmd = {
        "agent": "perception",
        "task": "assess crowd at Gate 4",
        "params": {"location": "Gate 4"},
    }
    r.rpush("commands", json.dumps(cmd))
    logger.info("Seeded command: %s", cmd)


def collect_reports(r: redis.Redis) -> list[dict]:
    """Read and clear all entries from the 'agent_reports' list."""
    pipe = r.pipeline()
    pipe.lrange("agent_reports", 0, -1)
    pipe.delete("agent_reports")
    results = pipe.execute()

    reports = []
    for raw in results[0]:
        try:
            reports.append(json.loads(raw))
        except json.JSONDecodeError:
            reports.append({"raw": raw})
    return reports


def main() -> None:
    r = get_redis()

    # Clean slate
    r.delete("commands", "agent_reports", "events")

    seed_command(r)

    agent = PerceptionAgent()
    thread = threading.Thread(target=agent.run, daemon=True, name="perception")
    thread.start()

    logger.info("Perception agent running for %d seconds — waiting for reports…", RUN_DURATION)
    time.sleep(RUN_DURATION)

    agent.stop()
    thread.join(timeout=7)

    reports = collect_reports(r)

    print("\n" + "=" * 50)
    print("  Reports generated by PerceptionAgent")
    print("=" * 50)
    if reports:
        for i, report in enumerate(reports, 1):
            print(f"\n[{i}]  {json.dumps(report, indent=4)}")
    else:
        print("\n  (no reports generated)")
    print()


if __name__ == "__main__":
    main()
